version: '3.8'

services:
  web:
    image: "nginx"
    volumes:
      - ./.docker/conf/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 81:80
    restart: always
    depends_on:
      - php-fpm
      - db
    env_file:
        -   .env
  php-fpm:
    build:
      context: .docker
      dockerfile: Dockerfile
    restart: always
    depends_on:
        - db
    volumes:
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./.docker/conf/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_HOST=${DB_HOST}
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_CONNECTION=${DB_CONNECTION}
        - POSTGRES_PORT=${DB_PORT}
    ports:
      - 54322:5432

  rabbitmq:
      image: rabbitmq:3.12.7-management
      hostname: rabbitmq
      restart: always
      environment:
          - RABBITMQ_DEFAULT_USER=user
          - RABBITMQ_DEFAULT_PASS=user
      ports:
          - 15672:15672
