version: '3.8'

services:
  web:
    image: "nginx:stable-alpine"
    volumes:
      - ./.docker/conf/nginx:/etc/nginx/conf.d
      - ./src:/var/www/html
    ports:
      - 8888:80
    restart: always
    depends_on:
      - php-fpm
      - db
  php-fpm:
    build:
      context: .docker
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./src:/var/www/html
    env_file:
      - .env

  db:
    image: postgres:latest
    volumes:
      - ./.docker/conf/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 54322:5432

  composer:
    build:
      context: .docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .docker
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]